# Generated by Django 4.0.5 on 2022-06-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('email', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('message', models.TextField(max_length=2000)),
                ('ip', models.CharField(max_length=200)),
                ('create_date', models.DateField(auto_now=True)),
                ('create_time', models.TimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqa',
            },
        ),
    ]
