# Generated by Django 4.0.5 on 2022-06-09 08:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000)),
                ('sub_title', models.TextField(blank=True, max_length=1000)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Sertifikat', max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/certificate/')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikat',
            },
        ),
        migrations.CreateModel(
            name='HozirgiSon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1001)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='images/hozirgison/')),
                ('pdf_file', models.FileField(upload_to='pdf/hozirgison/')),
                ('create_time', models.TimeField(auto_now=True)),
                ('create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hozirgi Son',
                'verbose_name_plural': 'Hozirgi Son',
            },
        ),
        migrations.CreateModel(
            name='Indexing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/indexing/')),
                ('link', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('link', models.SlugField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Information',
            },
        ),
        migrations.CreateModel(
            name='Konferensiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='images/konferensiya/')),
                ('pdf_file', models.FileField(upload_to='pdf/konferensiya/')),
                ('create_time', models.TimeField(auto_now=True)),
                ('create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konferensiya',
                'verbose_name_plural': 'Konferensiya',
            },
        ),
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, db_column='Upload an Image', default='images/default/default.jpg', null=True, upload_to='images/maqola/')),
                ('pdf_file', models.FileField(upload_to='pdf/maqola/')),
                ('create_time', models.TimeField(auto_now=True)),
                ('create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqola',
            },
        ),
        migrations.CreateModel(
            name='Arxiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maqola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maqola', to='home.maqola')),
            ],
            options={
                'verbose_name': 'Arxiv',
                'verbose_name_plural': 'Arxiv',
            },
        ),
    ]
