# Generated by Django 4.0.5 on 2022-06-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexing',
            options={'verbose_name': 'Indexing', 'verbose_name_plural': 'Indexing'},
        ),
        migrations.AlterField(
            model_name='indexing',
            name='link',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='information',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
