# Generated by Django 4.0.5 on 2022-06-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
