# Generated by Django 4.1.2 on 2022-10-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maqola',
            name='description',
        ),
    ]
